config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    resources :votes, only: [:create, :destroy]
  end
  resources :teams
  devise_for :users
  resources :users
  get "/dashboard", to: "home#dashboard"
  root "home#index"
end

app/views/shared/_side_nav.html.erb
<nav id='sidebarMenu' class="col-md-2 d-md-block bg-light sidebar collapse mt-4">
  <div class="sidebar-sticky pt-3">
    <% if Rails.env.development? %>
      <%= switch_user_select %>
    <% end %>
    <% if current_user %>
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to teams_path, class: "nav-link #{'active' if controller_name == 'teams'}" do %>
            <span data-feather="users"></span>
            Teams and Leaderboard
            <% if controller_name == 'teams' %>
              <span class="sr-only">(current)</span>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to submissions_path, class: "nav-link #{'active' if controller_name == 'submissions'}" do %>
            <span data-feather="git-pull-request"></span>
            Submissions
            <% if controller_name == 'submissions' %>
              <span class="sr-only">(current)</span>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link #{'active' if controller_name == 'users'}" do %>
            <span data-feather="users"></span>
            Users
            <% if controller_name == 'users' %>
              <span class="sr-only">(current)</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark navbar-expand-md flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-12 col-md-2 mr-0 px-3" href="/">Switch_ <br />Presents Hacktoberfest</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav px-3 col-sm-12 col-md-10 flex-column-reverse flex-md-row-reverse">
    <li class="nav-item text-nowrap">
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
      <% end%>
    </li>
    <% if current_user %>
      <li class="nav-item dropdown <%= 'active' if ['users'].include?(controller_name) %>">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag(current_user.gravatar_url(25), width: 25, alt: current_user.display_name, class: 'rounded-circle') %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
          <%= link_to "Profile", current_user, class: 'dropdown-item' %>
          <%= link_to "Change password", edit_user_registration_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% if current_user.team %>
        <li class="nav-item text-nowrap">
          <% votes_left = MAXIMUM_VOTES_PER_TEAM - current_user.votes.count %>
          <span class="nav-link">Your team has <%= pluralize(votes_left, "vote") %> left.
            <% if votes_left > 0 %>
              <%= link_to "Go vote!", submissions_path %>
            <% end %>
          </span>
        </li>
      <% else %>
        <li class="nav-item text-nowrap">
          <span class="nav-link">
            Join a team to be able to vote!
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>