config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    resources :votes, only: [:create, :destroy]
  end
  resources :teams
  devise_for :users
  resources :users
  get "/dashboard", to: "home#dashboard"
  root "home#index"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  has_one :team, through: :user
  has_many :votes, dependent: :destroy

  scope :most_loved, -> { order('votes_count DESC') }

  validates :project_name, presence: true
  validates :url, presence: true

  def pr_state
    return :invalid unless url.include?('github.com')

    github = Octokit::Client.new(:access_token => ENV['GITHUB_PERSONAL_TOKEN'])

    parts = url.split("/")
    org_repo = "#{parts[3]}/#{parts[4]}"
    pull_number = parts.last
    pr = github.pull_request(org_repo, pull_number)

    return "merged" if pr.merged?

    pr.state
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]
  authorize_resource

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.most_loved.page(params[:page]).per(1000)
  end

  # GET /submissions/1 or /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)
    @submission.user = current_user

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:project_name, :url)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def pr_status state
    color, icon = if state == "open"
              ["info", "clock"]
            elsif state == "merged"
              ["success", "check"]
            else
              ["danger", "x-circle"]
            end
    content_tag(:span, title: state, class: "text-#{color}") do
      content_tag(:span, nil, data: { feather: icon })
    end
  end
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prevented submission from being saved:</h2>

      <ul>
        <% submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :project_name, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :project_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url, class: "col-sm-2 col-form-label" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<% content_for :page_title, Submission.model_name.human %>
<% content_for :actions do %>
  <%= link_to("Show", @submission,
    class: 'btn btn-sm btn-outline-secondary')
    .concat(link_to("Back", submissions_path,
    class: 'btn btn-sm btn-outline-secondary')) %>
<% end %>

<%= render 'form', submission: @submission %>

app/views/submissions/index.html.erb
<% content_for :page_title, "Submissions" %>
<% content_for :actions do %>
  <%= link_to "New", new_submission_path,
    class: 'btn btn-sm btn-outline-primary' %>
<% end %>

<%= page_entries_info @submissions %>
<table class="table table-sm table-stripped">
  <thead>
    <tr>
      <th>State</th>
      <th><%= Submission.human_attribute_name(:project_name) %></th>
      <th><%= Submission.human_attribute_name(:url) %></th>
      <th>QR Code</th>
      <th>Submitter</th>
      <th># Votes</th>
      <th>Actions</th>
      <th>Vote!</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= pr_status(submission.pr_state) %></td>
        <td>
          <%= submission.project_name[0, 250] %>
          <% if current_user.voted_for?(submission) %>
            <span title="You voted for this!">
              <span data-feather="star" class="text-primary" title="You voted for this"></span>
            </span>
          <% end %>
          <% if submission.team == current_user.team %>
            <span title="From your team">
              <span data-feather="shield" class="text-success" title="From your team"></span>
            </span>
          <% end %>
        </td>
        <td><%= link_to submission.url, submission.url, target: "_blank" %></td>
        <td>
          <% if submission.url %>
            <%
                qrcode = RQRCode::QRCode.new(submission.url)
                svg = qrcode.as_svg(
                  color: "000",
                  shape_rendering: "crispEdges",
                  module_size: 11,
                  standalone: true,
                  use_path: true,
                  viewbox: true
                )
            %>
          <div style="width: 50px"><%= svg.html_safe %></div>
          <% end %>
        <td>
          <%= submission.team ? link_to(submission.team.name, submission.team) : link_to(submission.user.display_name, submission.user) %>
        </td>
        <td><%= submission.votes_count %></td>
        <td>
          <%= link_to "Show", submission %>
          <% if submission.user == current_user %>
            <%= link_to "Destroy", submission, method: :delete, data: { confirm: I18n.t('views.actions.confirm_destroy') } %>
          <% end %>
        </td>
        <td>
          <% unless current_user.team %>
            Join a team so you can vote
          <% end %>
          <% if current_user.admin? %>
            <% if current_user.can_vote_for?(submission) %>
              <%= form_with(model: [submission, Vote.new], local: true) do |form| %>
                <%= button_tag class: "btn text-success d-inline", title: "Vote!" do %>
                  <span data-feather="star"></span>
                <% end %>
              <% end %>
            <% elsif current_user.voted_for?(submission) %>
              <%= form_with(model: [submission, current_user.votes.where(submission_id: submission.id).first], local: true, method: :delete) do |form| %>
                <%= button_tag class: "btn text-danger", title: "Delete vote" do %>
                  <span data-feather="trash"></span>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<% content_for :page_title, Submission.model_name.human %>
<% content_for :actions do %>
  <%= link_to("Back", submissions_path,
    class: 'btn btn-sm btn-outline-secondary') %>
<% end %>

<%= render 'form', submission: @submission %>

app/views/submissions/show.html.erb
<% if current_user.admin? %>
  <% content_for :actions do %>
    <%= link_to("Edit", edit_submission_path(@submission),
      class: 'btn btn-sm btn-outline-primary')
      .concat(link_to("Back", submissions_path,
      class: 'btn btn-sm btn-outline-secondary')) %>
  <% end %>
<% else %>
  <% content_for :actions do %>
    <%= link_to("Back", submissions_path, class: 'btn btn-sm btn-outline-secondary') %>
  <% end %>
<% end %>
<p>
  <strong><%= Submission.human_attribute_name(:project_name) %>:</strong>
  <%= @submission.project_name %>
</p>

<p>
  <strong><%= Submission.human_attribute_name(:url) %>:</strong>
  <%= link_to @submission.url, @submission.url, target: '_blank' %>
</p>

<p>
  <strong><%= Submission.human_attribute_name(:user_id) %>:</strong>
  <%= link_to @submission.user.display_name, @submission.user %>
</p>